package: wk-ttyjs
user: wakari

install:
    - conda config --system --add channels https://conda.binstar.org/wakari

script:
  - conda build conda.recipe

build_targets: conda

notifications:
  email: 
    recipients: bkreider@continuum.io


