package:
  name: tty.js 
  version: 1.0 

source:
  git_url: git@github.com:ContinuumIO/tty.js.git


requirements:
  build:
    - python
    - nodejs
  run:
    - python
    - nodejs

about:
  home: https://github.com/ContinuumIO/tty.js
  license: MIT 
