package:
  name: tty.js 
  version: 1.0 

source:
  git_url: git@github.com:ContinuumIO/tty.js.git


requirements:
  build:
    - python
    - nodejs
  run:
    - python
    - nodejs

# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 1


about:
  home: https://github.com/ContinuumIO/tty.js
  license: MIT 
