package:
  name: tty.js 
  version: 1.0 

source:
  git_url: git@github.com:ContinuumIO/tty.js.git

build:            # (optional)
  number: 1 

requirements:
  build:
    - python   # needed for node-gyp
    - nodejs
  run:
    - nodejs

test:
    requires:
        - python
about:
  home: https://github.com/ContinuumIO/tty.js
  license: MIT 
